# Generated by Django 3.2.8 on 2021-11-15 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('especie', models.CharField(max_length=255, verbose_name='Espécie/tipo')),
                ('raca', models.CharField(max_length=255, verbose_name='Raça')),
                ('sexo', models.CharField(choices=[('F', 'Fêmea'), ('M', 'Macho'), ('N', 'Não informado')], max_length=20, verbose_name='Sexo')),
                ('notas', models.TextField(verbose_name='Observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.clientes', verbose_name='Cliente')),
            ],
            options={
                'verbose_name_plural': 'Pets',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preço')),
                ('detalhes', models.TextField(verbose_name='Observações')),
            ],
            options={
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preço')),
                ('data', models.DateField(verbose_name='Data da venda')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.clientes', verbose_name='Cliente')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.pet', verbose_name='Pet')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.services', verbose_name='Serviço')),
            ],
            options={
                'verbose_name_plural': 'Vendas',
            },
        ),
    ]
