# Generated by Django 3.2.8 on 2021-11-09 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0002_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('especie', models.CharField(max_length=255)),
                ('raca', models.CharField(max_length=255)),
                ('sexo', models.CharField(choices=[('F', 'Fêmea'), ('M', 'Macho'), ('I', 'Indefinido')], max_length=20)),
                ('notas', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.clientes')),
            ],
        ),
    ]
