# Generated by Django 3.2.8 on 2021-11-11 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0003_pet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name_plural': 'Pets'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterField(
            model_name='pet',
            name='sexo',
            field=models.CharField(choices=[('F', 'Fêmea'), ('M', 'Macho'), ('N', 'Não informado')], max_length=20),
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=9)),
                ('data', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.clientes')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.pet')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.services')),
            ],
            options={
                'verbose_name_plural': 'Vendas',
            },
        ),
    ]
