# Generated by Django 3.2.8 on 2021-11-13 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0005_services_detalhes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.CharField(max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='endereco',
            field=models.CharField(max_length=100, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.clientes', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='especie',
            field=models.CharField(max_length=255, verbose_name='Espécie/tipo'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='notas',
            field=models.TextField(verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='raca',
            field=models.CharField(max_length=255, verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sexo',
            field=models.CharField(choices=[('F', 'Fêmea'), ('M', 'Macho'), ('N', 'Não informado')], max_length=20, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.clientes', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='data',
            field=models.DateField(verbose_name='Data da venda'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.pet', verbose_name='Pet'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.services', verbose_name='Serviço'),
        ),
        migrations.AlterField(
            model_name='services',
            name='detalhes',
            field=models.TextField(verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='services',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='services',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preço'),
        ),
    ]
