# Generated by Django 3.2.8 on 2021-11-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0006_auto_20211113_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Email'),
        ),
    ]
