# Generated by Django 3.2.8 on 2021-11-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0008_auto_20211113_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.CharField(blank=True, max_length=100, verbose_name='Email'),
        ),
    ]
