# Generated by Django 3.2.8 on 2021-11-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0009_alter_clientes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='data',
            field=models.DateField(verbose_name='Data (dd/mm/aaaa)'),
        ),
    ]
