# Generated by Django 3.2.8 on 2021-11-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0010_alter_sales_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='data',
            field=models.DateField(verbose_name='Data da venda'),
        ),
    ]
